Dev branch
gadzira/anti-bruteforce pull request #1
Opened 2021-04-27 07:12 UTC by gadzira

Что сделал:
- Реализовал описанные в ТЗ методы
- Хранилище бакетов
- Пакет для работы с базой
- Пакет для работы с конфиг файлом
- Добавил файл миграции

Что НЕ сделал:
- CI
- Тесты
- CLI
- Make file

2021-05-02 10:05 UTC, farir1408 approved these changes

2021-05-02 10:05 UTC, farir1408 commented on cmd/antibruteforce/config.go
> +func NewConfig(fileName string) Config {
Я бы предложил сделать метод NewFromFile(), сейчас многие конфиги получают из env, и в будущем можно просто добавить метод NewFromEnv.

2021-05-02 10:05 UTC, farir1408 commented on cmd/antibruteforce/config.go
> +package main
Можно вынести в отдельный пакет `internal/config/`

2021-05-02 10:05 UTC, farir1408 commented on cmd/antibruteforce/main.go
> +func init() {
Есть крутая библиотека для написания cli - https://github.com/spf13/cobra . В данном случае можно оставить всё как сейчас, но прочитать про кобру рекомендую)

2021-05-02 10:05 UTC, farir1408 commented on internal/app/app.go
> +	DB      *db.DataBase
Зависимость на реализацию. Давайте опишем интерфейс, и заменим зависимость на этот интерфейс. Интерфейс можно положить например в `internal/domain/interfacec.go`

2021-05-02 10:05 UTC, farir1408 commented on internal/db/db.go
> +	db *sql.DB
Рекомендую использовать sqlx.

2021-05-02 10:05 UTC, farir1408 commented on internal/server/http/middleware.go
> +package internalhttp
Это лучше так и вынести в пакет middleware.

2021-05-02 10:05 UTC, farir1408 commented on internal/storage/storage.go
> +func (s *StorageOfBuckets) CheckRequest(log, pass, ip string) (bool, error) {
Метод довольно сложно читается. Возможно можно вынести каждый case в отдельную функцию?

2021-05-02 10:05 UTC, farir1408 requested changes
Жду доработки, + хочется видеть тесты. Не забывайте про них)

2021-05-02 17:51 UTC, gadzira commented on cmd/antibruteforce/main.go
> +func init() {
Ок, изучу!

2021-05-03 09:14 UTC, gadzira commented on internal/server/http/middleware.go
> +package internalhttp
Я не смогу объявить ресивер в другом пакете, тогда нужно будет из метода делать функцию.

2021-05-10 09:28 UTC, farir1408 commented on cmd/antibruteforce/main.go
> +			return
Возможно стоит завершаться тут с ошибкой.

2021-05-10 09:28 UTC, farir1408 commented on internal/app/app.go
> +func New(i interface{}) *domain.App {
Не совсем понятно зачем так сделано, лучше просто передавать параметры в функцию, более читабельно.

2021-05-10 09:28 UTC, farir1408 commented on internal/database/database.go
> +	if err := s.db.Ping(); err != nil {
Лишнее действие, не понятно зачем оно.

2021-05-10 09:28 UTC, farir1408 commented on internal/database/database.go
> +	rows, err := s.db.QueryContext(ctx, `SELECT cidr FROM list WHERE list = $1`, list)
Посмотрите на SelectContext, он тут позволит упростить код.

2021-05-10 09:28 UTC, farir1408 commented on internal/database/database_test.go
> +	ctx, cancel := context.WithCancel(context.Background())
В каждом тесте есть повторяющиеся действия. Посмотрите testify.Suite, там есть SetUp и TearDown, либо 
 testing.Main, и туда можно будет  вынести соединение с бд, и очистку бд после каждого тест-кейса.

2021-05-10 09:28 UTC, farir1408 commented on internal/domain/interface.go
> +	DB      *database.DataBase
Зависимость на интерфейс, интерфейс положите прямо в этот же пакет. Пакет domain не должен зависеть от кого-то, все зависят от него.

2021-05-10 09:28 UTC, farir1408 commented on internal/domain/interface.go
> +	New(i interface{}) *App
Конструктор обычно не выносят в интерфейс. Там обычно методы, которые будут использоваться, это делается, что бы отвязаться от конкретной реализации компонента.

2021-05-10 09:28 UTC, farir1408 commented on internal/server/http/server.go
> +		bl := a.Storage.ShowBuckets()
сторедж должен быть скрыт, лучше сделать его приватным у структуры App, и уже тут использовать метод App, который внутри вызывает storage.ShowBuckets().

2021-05-11 08:27 UTC, gadzira commented on internal/database/database.go
> +	rows, err := s.db.QueryContext(ctx, `SELECT cidr FROM list WHERE list = $1`, list)
Если честно, то у меня не получается сделать проще, тк SelectContext не умеет в пустые строчки (Scan error on column index 0, name "cidr": unsupported Scan, storing driver.Value type string into type *database.CIDR). А на начало работы программы white/black lists пустые.

2021-05-17 14:16 UTC, farir1408 commented on internal/database/database.go
> +	rows, err := s.db.QueryContext(ctx, `SELECT cidr FROM list WHERE list = $1`, list)
Для таких случаев можно определить кастомный тип и реализовать у него методы Scan и Value.

2021-05-17 14:21 UTC, farir1408 approved these changes

2021-05-17 14:23 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение проектного задания.

Отличная работа, прошли с Вами несколько стадий ревью, всё было исправлено и обсуждено. Принято 15/15.

2021-05-17 17:40 UTC, merged